# vi /etc/netplan/00-installer-config.yaml
# sudo netplan apply
network:                                                                                                                    
  ethernets:                                                                                                                
    enp0s31f6:                                                                                                              
      dhcp4: false                                                                                                          
      addresses:                                                                                                            
        - 192.168.0.115/24                                                                                                  
      nameservers:                                                                                                          
          addresses: [208.67.222.222]                                                                                       
  version: 2   
